
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InsulinDoseCalculator", targetNamespace = "http://server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InsulinDoseCalculator {


    /**
     * 
     */
    @WebMethod(operationName = "InsulinDoseCalculator")
    @RequestWrapper(localName = "InsulinDoseCalculator", targetNamespace = "http://server/", className = "client.InsulinDoseCalculator_Type")
    @ResponseWrapper(localName = "InsulinDoseCalculatorResponse", targetNamespace = "http://server/", className = "client.InsulinDoseCalculatorResponse")
    @Action(input = "http://server/InsulinDoseCalculator/InsulinDoseCalculatorRequest", output = "http://server/InsulinDoseCalculator/InsulinDoseCalculatorResponse")
    public void insulinDoseCalculator();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloWorldFrom", targetNamespace = "http://server/", className = "client.SayHelloWorldFrom")
    @ResponseWrapper(localName = "sayHelloWorldFromResponse", targetNamespace = "http://server/", className = "client.SayHelloWorldFromResponse")
    @Action(input = "http://server/InsulinDoseCalculator/sayHelloWorldFromRequest", output = "http://server/InsulinDoseCalculator/sayHelloWorldFromResponse")
    public String sayHelloWorldFrom(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "backgroundInsulinDose", targetNamespace = "http://server/", className = "client.BackgroundInsulinDose")
    @ResponseWrapper(localName = "backgroundInsulinDoseResponse", targetNamespace = "http://server/", className = "client.BackgroundInsulinDoseResponse")
    @Action(input = "http://server/InsulinDoseCalculator/backgroundInsulinDoseRequest", output = "http://server/InsulinDoseCalculator/backgroundInsulinDoseResponse")
    public double backgroundInsulinDose(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mealtimeInsulinDose", targetNamespace = "http://server/", className = "client.MealtimeInsulinDose")
    @ResponseWrapper(localName = "mealtimeInsulinDoseResponse", targetNamespace = "http://server/", className = "client.MealtimeInsulinDoseResponse")
    @Action(input = "http://server/InsulinDoseCalculator/mealtimeInsulinDoseRequest", output = "http://server/InsulinDoseCalculator/mealtimeInsulinDoseResponse")
    public float mealtimeInsulinDose(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4);

}
